framework:
    messenger:
        failure_transport: failed
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 10
                    max_delay: 0
                options:
                    queue_name: 'async'
                    auto_setup: true
            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: 'failed'
                    auto_setup: true
            sync: 'sync://'

        routing:
            'App\Message\AsyncMessageInterface': async

        default_bus: command.bus

        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            query.bus: ~
            event.bus: ~